In [1]:
1+1

2

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [30]:
pix_size = 200e-6
to_nm = lambda e: 1239.84193 / e * 1e-9
to_eV = lambda l: 1239.84193 / (l * 1e9)

A_ = (1/1e-10)
ring_center = 2* A_
ring_range = (1.2*A_, 3*A_)


def theta_from_q_lambda(q,lm):
    return 2*np.arcsin((np.array(q)*lm)/(4*np.pi))
def theta_from_energy(q,e):
    return theta_from_q_lambda(q, to_nm(e))

def r_from_theta_d(theta, d):
    return d * np.tan(theta)

In [49]:
2*np.pi/(3*A_)

2.0943951023931955e-10

In [14]:
t_range = np.radians((11.3,28.7))
t_range

array([0.19722221, 0.5009095 ])

In [22]:
theta_from_energy(ring_range,15e3)

array([0.15802595, 0.33037877])

In [60]:
d=5e-2

r_from_theta_d(theta_from_energy(ring_range,12e3),d)/1e-3

array([10.01315503, 27.21534731])

0.0256

In [56]:
1.1 /0.9

1.2222222222222223

In [57]:
1.03/0.97


1.0618556701030928